config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get  '/about' => 'static_pages#about'

  get 'users', to: 'users#index'


  post 'users/create', to: 'users#create', as: 'create_user'
  post 'users', to: 'users#index', as: 'search'
  get '/new', to: 'users#new', as: 'signup'

  get 'users/:id', to: 'users#show', as: 'user_profile'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user_profile'
  patch 'users/:id', to: 'users#update', as: 'update_user_profile'
  delete 'users/:id', to: 'users#destroy', as: 'delete_user_profile'

  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :block_relationships,       only: [:create, :destroy]

  resources :winks,       only: [:create]


  resources :users do
    member do
      get :blocking
      get :wink_senders, :wink_recipients
    end
  end

  get 'users/instagram/add' => 'users#instagramadd'
  get '/users/oauth/callback' => 'users#instagram_callback'


  post '/users/sendmessage/:id' => 'users#send_email' ,as: 'sendemail'

#   get "/users/instagram" do
#     redirect Instagram.authorize_url(:redirect_uri => CALLBACK_URL, :scope => 'comments relationships likes')
#   end
#
#   get "/users/instagram" do
#     response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
#     session[:access_token] = response.access_token
#     redirect "/feed"
#   end
# #
#   get "/feed" do
#     client = Instagram.client(:access_token => session[:access_token])
#     user = client.user
# end
#
# get "/" do
#   '/users/instagram/add'
# end
#
# get "/access_token" do
#   'access_token: ' + session[:access_token]
# end



end

app/models/user.rb
class User < ApplicationRecord
  has_many :active_winks, class_name:  "Wink",
                                  foreign_key: "wink_sender_id",
                                  dependent:   :destroy
  has_many :passive_winks, class_name:  "Wink",
                                  foreign_key: "wink_recipient_id",
                                  dependent:   :destroy

  has_many :active_block_relationships, class_name:  "BlockRelationship",
                                foreign_key: "blocker_id",
                                dependent:   :destroy
  has_many :passive_block_relationships, class_name:  "BlockRelationship",
                               foreign_key: "blocked_id",
                               dependent:   :destroy

  has_many :blocking, through: :active_block_relationships, source: :blocked
  has_many :blockers, through: :passive_block_relationships, source: :blocker

  has_many :wink_recipients, through: :active_winks
  has_many :wink_senders, through: :passive_winks

    # attr_accessible :email, :password, :password_confirmation
  attr_accessor :remember_token, :activation_token, :reset_token

  validates :full_name,  presence: true, length: { maximum: 50 }

  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX, message: "not valid"},
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 3 }, allow_nil: true
  has_secure_password

  validates_inclusion_of :age, in: 18..120, message: "Must be 18 years or older to signup!"
  validates_numericality_of :age, only_integer: true, allow_nil: false, message: "Must enter in age as a whole integer!"

  mount_uploader :video, VideoUploader
  mount_uploader :image, ImageUploader

 #-----------------------------------------------------------------------------------------------------

  def index
    @user = User.where(gender: current_user.sexual_preference).all
  end

  def new
    @user = User.new
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Checks whether a password is needed or not. For validations only.
  # Passwords are always required if it's a new record, or if the password
  # or confirmation are being set somewhere.
  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  # Returns a random token (for remember me sign-in option)
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  #-----------------------------------------------------------------------------------------------------
  # METHODS FOR PASSWORD RESET

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  #-----------------------------------------------------------------------------------------------------
  # METHODS FOR USER BLOCKING FUNCTIONALITY

  def block(other_user)
    blocking << other_user
  end

  def unblock(other_user)
    blocking.delete(other_user)
  end

  # Returns true if the current user is blocking the other user.
  def blocking?(other_user)
    blocking.include?(other_user)
  end

  #-----------------------------------------------------------------------------------------------------
  # METHODS FOR USER WINKING FUNCTIONALITY

  def wink_at(other_user)
    wink_recipients << other_user
  end

  def winked_at?(other_user)
    wink_recipients.include?(other_user)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # \/ Requires user to be logged in before editing, updating, or viewing index
    before_action :logged_in_user, only: [:index, :edit, :update, :blocking]

  # \/ Requires that one be the user of the profile page one is trying to edit or destroy
    before_action :correct_user,   only: [:edit, :update, :destroy, :blocking]

  # \/ Reqires that current_user not be blocked by show-page user in order to view their show page
    before_action :user_not_blocked, only: :show

# enable :sessions
    # For secured endpoints only
    #config.client_ips = '<Comma separated list of IPs>'

  #-------------------------------------------------------------------------------------------------------------------------------------
  def index
    if current_user.sexual_preference == "male" && current_user.gender == "male"
        @user = User.where(gender: "male").where(sexual_preference: "male")
    elsif  current_user.sexual_preference == "female" && current_user.gender == "female"
        @user = User.where(gender: "female").where(sexual_preference: "female")
    else
        @user = User.where(gender: current_user.sexual_preference)
    end

    if params[:search].present?
      if params[:search][:age_from].present? && params[:search][:age_to].present?
        @user = @user.where("age > ? and age < ?",params[:search][:age_from].to_i,params[:search][:age_to].to_i)
      elsif params[:search][:children].present? && params[:search][:children] == "yes"
        @user = @user.where.not(children: "")
      elsif params[:search][:height_from].present? && params[:search][:height_to].present?
        @user = @user.where("height > ? and height < ?",params[:search][:height_from], params[:search][:height_to])
      elsif params[:search][:ethnicity].present?
        @user = @user.where(ethnicity: params[:search][:ethnicity])
      end
    end
  end


  def new
      @user = User.new
  end

  def show
   @user = User.find(params[:id])
   @users = @user.wink_senders
   @insta_feed = Instagram.client(:access_token => @user.instagram_token)
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
         flash[:success] = "User Profile Successfully Created"
         # Tells the UserMailer to send a welcome email after save
         UserMailer.welcome_email(@user).deliver_now

        #  if @user.sexual_preference == "m4f"
        #    render 'm4f'
        #  elsif @user.sexual_preference == ")f4m"
        #    render 'f4m'
        #  elsif @user.sexual_preference == "m4m"
        #    render 'm4m'
        #  else @user.sexual_preference == "f4f"
        #      render 'f4f'
        #    end}
          format.html { redirect_to(users_path, notice: 'User was successfully created.') }
          format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    @user = User.find(params[:id])  # Could technically delete this line because of the correct_user user method and filter? (line 5)
  end

  def update
    @user = User.find(params[:id])  # Could technically delete this line because of the correct_user user method and filter? (line 5)
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_profile_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "You have deleted your account, including all profile information!"
    redirect_to users_url
  end

  #-------------------------------------------------------INSTAGRAM-------------------------------------------------------------------
  # Instagram callback in process
   def instagramadd
     redirect_to Instagram.authorize_url(:redirect_uri => "http://localhost:3000/users/oauth/callback")
   end

   def instagram_callback
     response = Instagram.get_access_token(params[:code], :redirect_uri => "http://localhost:3000/users/oauth/callback")
    if current_user
      current_user.instagram_token = response.access_token
    if current_user.save
    redirect_to user_profile_path(current_user.id)
    end
    end

   end

  #-------------------------------------------------------------------------------------------------------------------------------------
  # User can send email to another user
  def send_email
    UserMailer.send_message(params[:id],params[:message][:message]).deliver_now
    render html: 'You sent a message'
  end

  def wink
    UserMailer.send_message(params[:id],"You've been winked at ...").deliver_now
    render img
  end

  #-------------------------------------------------------------------------------------------------------------------------------------
  private

   def user_params
     params.require(:user).permit(:full_name, :gender, :age, :ethnicity, :children, :occupation, :email, :password, :video, :image, :password_confirmation, :sexual_preference)
   end


  # \/ Before filters

  # Filter method that disallows access to show page owner if they have blocked current user.

  def winks_received
    @user  = User.find(params[:id])
    @users = @user.wink_senders
    render 'show_wink_senders'
  end

  #-------------------------------------------------------------------------------------------------------------------------------------
  # Confirms that current_user is not blocked by @user
  def user_not_blocked
    @user = User.find(params[:id])
    if @user.blocking?(current_user)
                                                                          # unless not_blocked?
      flash[:danger] = "You have been blocked by #{@user.full_name}"
      redirect_to users_path
    end
  end

  def blocking                # Don't remember what this was for.
    @title = "Blocking"
    @user  = User.find(params[:id])
    @users = @user.blocking
  end

  #-------------------------------------------------------------------------------------------------------------------------------------
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location # This line uses a method in sessions_helper to store request location so that it may redirect them to that location upon login.
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(login_url) unless current_user?(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_block.html.erb
<%= form_for(current_user.active_block_relationships.build) do |f| %>
  <div><%= hidden_field_tag :blocked_id, @user.id %></div>
  <%= f.submit "Block", class: "btn btn-primary" %>
<% end %>

app/views/users/_block_form.html.erb
<% unless current_user?(@user) %>
  <div id="block_form">
  <% if current_user.blocking?(@user) %>
    <%= render 'unblock' %>
  <% else %>
    <%= render 'block' %>
  <% end %>
  </div>
<% end %>

app/views/users/_filter_searches.html.erb
<%= form_for :search,url: search_path do |f| %>
<h1> Search </h1>

<%= f.label :age_from%>
<%= f.text_field :age_from %>

<%= f.label :age_to%>
<%= f.text_field :age_to%>

<%= f.label :children %>
<%= f.select :children, ['no', 'yes']%>

<%= f.label :height_from %>
<%= f.select :height, ['152.40', '154.94','157.48','160.02','162.56','165.10','167.74','170.18','172.72','175.26','177.80','180.34','182.88','185.45','187.96','190.50','193.04','195.58']%>
<br>
<%= f.label :height_to %>
<%= f.select :height, ['152.40', '154.94','157.48','160.02','162.56','165.10','167.74','170.18','172.72','175.26','177.80','180.34','182.88','185.45','187.96','190.50','193.04','195.58']%>

<%= f.label :ethnicity %>
<%= f.select :ethnicity, User.distinct(:ethnicity).pluck(:ethnicity)%>
<%= f.submit "send" %>
<% end %>

app/views/users/_sendwink.html.erb
<%= form_for(current_user.active_winks.build) do |f| %>
  <div><%= hidden_field_tag :wink_recipient_id, @user.id %></div>
  <%= f.submit "Send wink", class: "btn btn-primary" %>
<% end %>

app/views/users/_show_wink_senders.html.erb
<span><b>Winks Received:</b> <%= @user.wink_senders.count %></span>
<section class="stats">
  <% if @users.any? %>
    <div class="user_pictures">
      <% @users.each do |user| %>
        <ul>
          <!-- <li class="user_picture"><%= user.image %></li> -->
          <li><a href="/users/<%=user.id%>"><%= user.full_name %></a></li>
        </ul>
      <% end %>
    </div>
  <% end %>
</section>

app/views/users/_unblock.html.erb
<%= form_for(current_user.active_block_relationships.find_by(blocked_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unblock", class: "btn" %>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit My Profile") %>
  <div class="title_h1">
    <h1>Update your profile</h1>
  </div>

  <div id="horse"></div>

  <div class="edit_row">

  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: "/users/#{@user.id}" do |f| %>

      <%= render 'shared/error_messages' %> <br>

      <%= f.label :full_name %>
      <%= f.text_field :full_name, placeholder: 'change name here', class: 'form-control' %> <br> <br>

      <%= f.label :email %>
      <%= f.email_field :email, placeholder: 'change email here', class: 'form-control' %> <br> <br>

      <%= f.label :ethnicity%>
      <%= f.text_field :ethnicity, placeholder: 'add ethnicity'%><br>

      <%= f.label :children %>
      <%= f.text_field :children, placeholder: 'add children'%><br>

      <%= f.label :video %>
      <%= f.file_field :video, placeholder: 'change or add video '%><br>

      <%= f.label :password %>
      <%= f.password_field :password, placeholder: 'add new password', class: 'form-control' %> <br> <br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %> <br>

      <%= f.submit "Save changes", class: "btn btn-primary" %> <br>
      <br>

      <% if !@user.instagram_token.present? %>
        <a href="/users/instagram/add">Connect your Instagram!</a>

      <%end %> <br>
      <br>
      <% if current_user?(@user) %>
      <%= link_to "Delete My Account", delete_user_profile_path, method: :delete,
                                      data: { confirm: "Are you sure? This cannot be undone!" } %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<body>

  <h4>PROFILES</h4>
  <div class="title_h1">
  <%= render 'filter_searches' %>
</div>
  <div class="container">
    <% @user.each do |user| %>

    <a href="/users/<%=user.id%>"><video src="<%= user.video.url %>"<video width="320" height="240" controls>/>

    <% end %>
</div>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="title_h1">
<h1> Sign Up </h1>
</div>

<div class="sign_up">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: create_user_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :full_name %>: <br>
      <%= f.text_field :full_name, class: 'form-control' %> <br> <br>

      <%= f.label :age %>: <br>
      <%= f.text_field :age %><br> <br>

      <%= f.label :children %>: <br>
      <%= f.text_field :children, :placeholder => "yes or no" %><br> <br>

      <%= f.label :ethnicity %>: <br>
      <%= f.text_field :ethnicity %><br> <br>

      <%= f.label :gender %>: <br>
      <%= f.select :gender, [ 'male','female' ] %> <br> <br>

      <%= f.label :occupation %>: <br>
      <%= f.text_field :occupation %><br> <br>

      <%= f.label :height %>: <br>
      <%= f.text_field :height, :placeholder => "in cm!" %><br> <br>

      <%= f.label :email %>: <br>
      <%= f.email_field :email, class: 'form-control' %> <br> <br>

      <%= f.label :video %>: <br>
      <%= f.file_field :video %> <br> <br>

      <!--
      <%= f.label :image %>
      <%= f.file_field :image %><br> -->

      <%= f.label :sexual_preference %>: <br>
      <%= f.select :sexual_preference, [ 'male','female' ] %> <br> <br>

      <%= f.label :password %> <br>
      <%= f.password_field :password, class: 'form-control' %> <br> <br>

      <%= f.label :password_confirmation, "Confirmation" %> <br>
      <%= f.password_field :password_confirmation, class: 'form-control' %> <br> <br>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div id="forest"></div>

app/views/users/show.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Special+Elite" rel="stylesheet">
</head>
  <div class="title_h1">
    <h1>Individual User Profile</h1>
  </div>

<div id="flower"></div>

  <div id="individual_profile_row">
  <% if current_user?(@user) # We do not want to display this link unless current user is visiting their own show page %>
    <%= link_to "Edit My Profile", edit_user_profile_path(@user) %>
  <% end %>

    <p><%= @user.full_name %></p>
    <h5><%= @user.age%></h5>
    <h5><%= @user.occupation %></h5>
<!-- <a href="/users/show/<%=@user.id%>"><img src="<%= @user.image.url %>"></a> -->

  <div id="video">
    <video width="320" height="240" controls>
    <source src="<%= @user.video.url%>">
    </video>
  </div>

</div>

  <div id="email_font">
    <p>Don't be shy ... send me a note ;)</p>
    <%= render 'sendwink' if logged_in? && !current_user?(@user) %>
  </div>


  <%= render 'show_wink_senders' if logged_in? && current_user?(@user) %>


  <%=form_for :message, url: sendemail_path(@user.id) do |f| %>
    <%= f.text_area :message , row: 10, cols: 210 %>
    <%= f.submit "send" %>

    <%end%>
    <% begin%>
      <%@insta_feed.user_recent_media.each do |img| %>
      <img src='<%=img.images.standard_resolution.url %>'>
      <% end %>
      <% rescue %>
      Instagram is not connected on this profile
      <%end %>

<%= render 'block_form' if logged_in? %>

app/views/users/show_block.html.erb
<!-- <% provide(:title, @title) %>
<div class="row">
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div> -->