config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get  '/about' => 'static_pages#about'

  get 'users', to: 'users#index'


  post 'users/create', to: 'users#create', as: 'create_user'
  post 'users', to: 'users#index', as: 'search'
  get '/new', to: 'users#new', as: 'signup'

  get 'users/:id', to: 'users#show', as: 'user_profile'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user_profile'
  patch 'users/:id', to: 'users#update', as: 'update_user_profile'
  delete 'users/:id', to: 'users#destroy', as: 'delete_user_profile'

  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :block_relationships,       only: [:create, :destroy]

  resources :winks,       only: [:create]


  resources :users do
    member do
      get :blocking
      get :wink_senders, :wink_recipients
    end
  end

  get 'users/instagram/add' => 'users#instagramadd'
  get '/users/oauth/callback' => 'users#instagram_callback'


  post '/users/sendmessage/:id' => 'users#send_email' ,as: 'sendemail'

#   get "/users/instagram" do
#     redirect Instagram.authorize_url(:redirect_uri => CALLBACK_URL, :scope => 'comments relationships likes')
#   end
#
#   get "/users/instagram" do
#     response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
#     session[:access_token] = response.access_token
#     redirect "/feed"
#   end
# #
#   get "/feed" do
#     client = Instagram.client(:access_token => session[:access_token])
#     user = client.user
# end
#
# get "/" do
#   '/users/instagram/add'
# end
#
# get "/access_token" do
#   'access_token: ' + session[:access_token]
# end



end

app/views/layouts/_header.html.erb
<!-- Header navbar rendered in application.html.erb, contains currently unused class names -->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   <div id="branding">
     <h1><%= link_to "NOBLE", root_path, id: "logo" %></h1>
   </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "How we're different",   about_path %></li>
        <% if logged_in? %>
          <li class="stats"><%= render 'shared/mywinks' %></li>
          <li><%= link_to "My dating pool", users_path %></li>
          <li><%= link_to "My profile", user_profile_path(@current_user.id) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>

        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>

    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Homemade+Apple|Lateef" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Special+Elite" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
  </head>

  <body>
     <%= render 'layouts/header' %>  <!-- This splits off the header into a seperate file for readability, see _header.html.erb in layouts -->


    <div class="container"> <!-- Currently there are unused class/id names such as container that a tutorial had me use. I might use them later. -->
      <%= yield %>
    </div>

    <footer>
      <p> FOOTER </p>
    </footer>

  </body>
</html>